Package Version update to 2.9.2
AnacondaRecipes/mlflow-feedstock pull request #5
Opened 2024-01-23 16:56 UTC by psteyer

Updating package due to being effected by multiple CVE's. 

CVE-2023-6753
CVE-2023-6831
CVE-2023-6018
CVE-2023-6974
CVE-2023-6975
CVE-2023-6976
CVE-2023-6940

Jira: https://anaconda.atlassian.net/browse/PKG-3694

### Changes
- updated version number
- updated SHA

2024-01-23 16:57 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_b848wzt47c/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:107: missing_pip_check: For pypi packages, pip check should be present in the test commands
- clone/recipe/meta.yaml:86: missing_pip_check: For pypi packages, pip check should be present in the test commands
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-01-23 18:45 UTC, JeanChristopheMorinPerso requested changes
The list of dependencies changed between 2.6.0 and 2.9.2. The list for the "snikky" variant can be found in https://github.com/mlflow/mlflow/blob/v2.9.2/requirements/skinny-requirements.txt and the list for the non snikky in https://github.com/mlflow/mlflow/blob/v2.9.2/requirements/core-requirements.txt. You can also find the stuff that is in `run_constrained` in https://github.com/mlflow/mlflow/blob/v2.9.2/requirements/extra-ml-requirements.txt.

2024-01-23 20:32 UTC, psteyer commented
I noticed there is also a difference between our `importlib-metadata` naming and the `skinny-requirments.txt`  ->`importlib_metadata`. Does this make a difference?

2024-01-23 20:34 UTC, JeanChristopheMorinPerso commented
No. The package names in Python are all normalized, which means that `-` is the same as `_`. Note that this behavior is specific to the python ecosystem and that it's different in the conda world. With conda `-` is different than `_`.

2024-01-23 21:59 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_d1wzfgmhz2/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:86: missing_pip_check: For pypi packages, pip check should be present in the test commands
- clone/recipe/meta.yaml:107: missing_pip_check: For pypi packages, pip check should be present in the test commands
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-01-23 22:00 UTC, psteyer commented
> The list of dependencies changed between 2.6.0 and 2.9.2. The list for the "snikky" variant can be found in https://github.com/mlflow/mlflow/blob/v2.9.2/requirements/skinny-requirements.txt and the list for the non snikky in https://github.com/mlflow/mlflow/blob/v2.9.2/requirements/core-requirements.txt. You can also find the stuff that is in `run_constrained` in https://github.com/mlflow/mlflow/blob/v2.9.2/requirements/extra-ml-requirements.txt.

I updated some requirement pinnings, but I couldn't find anything in https://github.com/mlflow/mlflow/blob/v2.9.2/requirements/extra-ml-requirements.txt

2024-01-24 00:42 UTC, danpetry commented on recipe/meta.yaml
>      - numpy <2.0
you could put `- numpy {{ numpy }}`, see cbc.yaml for the reason

2024-01-24 00:42 UTC, danpetry commented on recipe/meta.yaml
>      - jinja2 <4,>=3.0  # [win]
pytorch_lightning >=1.8.1
https://github.com/mlflow/mlflow/blob/6ca72469b289e77acc2f1201ca39237fc025c090/requirements/extra-ml-requirements.txt#L16

2024-01-24 00:42 UTC, danpetry commented on recipe/meta.yaml
>      - jinja2 <4,>=3.0  # [win]
also shap >=0.42.1

2024-01-24 00:42 UTC, danpetry commented on recipe/meta.yaml
>      - jinja2 <4,>=3.0  # [win]
and torch should be pytorch, I think torch is the pip name

2024-01-24 00:45 UTC, danpetry commented
packages in requirements.txt in repos refer to packages on pypi. Our recipes refer to conda packages. The names are usually the same but sometimes a bit different, so it's worth keeping an eye out for packages that have similar names when comparing our recipes with upstream repos

2024-01-24 00:48 UTC, danpetry commented
and yeah, always worth checking the deps haven't changed if you upgrade the version number. You can do a diff upstream via the pull request button (but not actually opening a PR) and checking whichever file the requirements are expressed in

2024-01-24 08:57 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - numpy <2.0
`- numpy {{ numpy }}` variant is only for `host`

2024-01-24 17:47 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
>      - jinja2 <4,>=3.0  # [win]
@danpetry `pytorch_lightning` should be removed. `lightning>=1.8.1` should be added and `openai<1.0` too.

2024-01-24 23:46 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_0efxw7upqj/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:109: missing_pip_check: For pypi packages, pip check should be present in the test commands
- clone/recipe/meta.yaml:88: missing_pip_check: For pypi packages, pip check should be present in the test commands
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-01-25 09:35 UTC, skupr-anaconda commented
```
conda.CondaError: Downloaded bytes did not match Content-Length
  url: https://pypi.io/packages/source/m/mlflow/mlflow-2.9.2.tar.gz
  target_path: /src_cache/src_cache/mlflow-2.9.2_25f2ad3d0b.tar.gz
  Content-Length: 18655983
```

2024-01-25 15:58 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_580i5brtla/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:88: missing_pip_check: For pypi packages, pip check should be present in the test commands
- clone/recipe/meta.yaml:109: missing_pip_check: For pypi packages, pip check should be present in the test commands
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>

2024-01-25 20:37 UTC, JeanChristopheMorinPerso approved these changes

2024-01-25 21:58 UTC, danpetry approved these changes

2024-01-26 21:51 UTC, merged

2024-01-26 21:52 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_485u9ppii5/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:88: missing_pip_check: For pypi packages, pip check should be present in the test commands
- clone/recipe/meta.yaml:109: missing_pip_check: For pypi packages, pip check should be present in the test commands
===== Final Report: =====
2 Errors and 0 Warnings were found

</details>